# Generated by Django 5.0.1 on 2024-01-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
